### ISSUE TITLE
'duplicate dependency' error

### ISSUE THREAD

**Issue by YKunneman** [DigitPaint/roger_babeljs#2]
Using this gem with bundler gives the following error:

```
The gemspec at ... /roger_babeljs.gemspec is not valid. The validation error was 'duplicate dependency on roger (>= 0, development), (>= 0.11.0) use:
    add_runtime_dependency 'roger', '>= 0', '>= 0.11.0'
```

**Comment by edwinvdgraaf** [comment]
I think this is caused, by [this line](https://github.com/DigitPaint/roger_babeljs/blob/master/roger_babeljs.gemspec#L28). 

But I also think `'>= 0.11.0'` must be updated to ensure compatibility with roger > 1.0.
